### ISSUE TITLE
Dev link not working

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Academic-Advising#1]
Hey L-Dogg, the dev link isn't displaying, it opens to a 404..

**Comment by lidopaglia** [comment]
fixed by [moving the street address](https://github.com/TULiberalArts/Academic-Advising/commit/d8b5ac9abe0e621b93ea8530a774ebccfcf8a8f2) to the correct key in `_config.yml`

**Comment by lidopaglia** [comment]
[build passed](https://travis-ci.org/TULiberalArts/Academic-Advising/builds/421263254) and files pushed to s3 successfully.
