### ISSUE TITLE
Please center hero

### ISSUE THREAD

**Issue by CVE82** [TULiberalArts/Academic-Advising#2]
Thank you! resizedetdstudents.jpg

**Comment by CVE82** [comment]
https://github.com/TULiberalArts/Academic-Advising/blob/master/media/resizedetdstudents.jpg

**Comment by ZMcGroarty** [comment]
![caapd-min](https://user-images.githubusercontent.com/15017242/44738717-cb3e4300-aac3-11e8-9180-3ccb9ac5a0a2.png)

**Comment by CVE82** [comment]
Thanks!
